    <main class="conteneur mainAbout">
        <section class="mainAbout_section-team">

            <h1>Notre équipe</h1>
            <article class="mainAbout_article-amelie clearfix">
                <h2 class="borderBar"><span>Amélie, fondatrice de Cup of Tea </span></h2>
                <img src="img/amelie.jpg" alt="" class="amelie">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, recusandae. Quod soluta
                    accusamus porro non quo cumque facilis. Ipsum enim at alias. Odit delectus deleniti veniam
                    voluptate inventore tempora nisi. <br> Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Quasi eos maxime vel velit deserunt nihil. Eum corporis ea fugit illum dolor natus, velit
                    repellendus, officiis suscipit ut, eveniet doloribus qui. <br> Lorem ipsum dolor sit amet,
                    consectetur adipisicing elit. Quisquam nemo quos porro excepturi, alias dolorem fugiat optio
                    cupiditate repellat hic reiciendis perspiciatis et in minima? Eos, quae sed. Ex, molestiae?</p>
            </article>
            <article class="mainAbout_article-xavier clearfix">
                <h2 class="borderBar"><span>Xavier, fondateur de Cup of Tea </span></h2>
                <img src="img/xavier.jpg" alt="" class="xavier">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, recusandae. Quod soluta
                    accusamus porro non
                    quo cumque facilis. Ipsum enim at alias. Odit delectus deleniti veniam voluptate inventore tempora
                    nisi. <br> Lorem
                    ipsum dolor sit amet consectetur adipisicing elit. Quasi eos maxime vel velit deserunt nihil. Eum
                    corporis ea fugit
                    illum dolor natus, velit repellendus, officiis suscipit ut, eveniet doloribus qui. <br> Lorem ipsum
                    dolor sit amet,
                    consectetur adipisicing elit. Quisquam nemo quos porro excepturi, alias dolorem fugiat optio
                    cupiditate repellat
                    hic reiciendis perspiciatis et in minima? Eos, quae sed. Ex, molestiae?</p>
            </article>
        </section>
        <article class="mainAbout_section-concept">
            <h1>Notre Concept</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, recusandae. Quod soluta
                accusamus porro non
                quo cumque facilis. Ipsum enim at alias. Odit delectus deleniti veniam voluptate inventore tempora
                nisi. Lorem
                ipsum dolor sit amet consectetur adipisicing elit. <br>Quasi eos maxime vel velit deserunt nihil.
                Eum corporis ea fugit
                illum dolor natus, velit repellendus, officiis suscipit ut, eveniet doloribus qui. Lorem ipsum
                dolor sit amet,
                consectetur adipisicing elit. Quisquam nemo quos porro excepturi, alias dolorem fugiat optio
                cupiditate repellat
                hic reiciendis perspiciatis et in minima? Eos, quae sed. Ex, molestiae?</p>
            <div class="mainAbout_div-concept">
                <div class="mainAbout_div-the-concept">
                    <img src="img/concept/1.svg" alt="">
                    <h3> Lorem ipsum</h3>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Non corporis id voluptates hic dicta
                        iure
                        unde voluptatibus facere quibusdam? Rem ut accusantium sit quaerat dolore temporibus voluptas
                        harum! Repellendus, laudantium. </p>
                </div>
                <div class="mainAbout_div-the-concept">
                    <img src="img/concept/2.svg" alt="">
                    <h3> Dolor</h3>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Non corporis id voluptates hic dicta
                        iure
                        unde voluptatibus facere quibusdam? Rem ut accusantium sit quaerat dolore temporibus voluptas
                        harum! Repellendus, laudantium. </p>
                </div>
                <div class="mainAbout_div-the-concept">
                    <img src="img/concept/3.svg" alt="">
                    <h3> Sit amet </h3>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Non corporis id voluptates hic dicta
                        iure
                        unde voluptatibus facere quibusdam? Rem ut accusantium sit quaerat dolore temporibus voluptas
                        harum! Repellendus, laudantium. </p>
                </div>
            </div>
        </article>

    </main>