<footer class="footer">
        <div class="footer-">
            <nav class="footer_nav-first-lg">
                <a href=""><i class="fas fa-lock"></i>Paiement sécursé</a>
                <a href=""><i class="fas fa-truck"></i>Ma livraison offerte</a>
                <a href=""><i class="far fa-money-bill-alt"></i>Carte de fidélité</a>
                <a href=""><i class="fas fa-phone"></i>Service Client</a>
                <a href=""><i class="fas fa-check-circle"></i>Garantie Qualité</a>
            </nav>
            <div class="footer_div-multinav">
                <nav class="footer_nav-cup-of-tea">
                    <h3>Cup of tea</h3>
                    <a href="">Notre histoire</a>
                    <a href="">Nos boutiques</a>
                    <a href="">Le thé de A à Z</a>
                    <a href="">Espace clients professionnels</a>
                    <a href="">Recrutement</a>
                    <a href="">Contatez-nous</a>
                    <a href="">L'école du thé</a>
                </nav>
                <nav class="footer_nav-online-order">
                    <h3>Commande en ligne</h3>
                    <a href="">Première visite</a>
                    <a href="">Aide - FAQ</a>
                    <a href="">Sevice client</a>
                    <a href="">Suivre ma commande</a>
                    <a href="">Condition générales de vente</a>
                    <a href="">INformation légales</a>
                </nav>
                <nav class="footer_nav-follow">
                    <h3>Suivez-nous</h3>
                    <a href="">Notre histoire</a>
                    <a href="">Nos boutiques</a>
                    <a href="">Le thé de A à Z</a>
                    <a href="">Espace clients professionnels</a>
                </nav>
            </div>
        </div>
    </footer>
    <script src="script/jquery-3.3.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="script/jquery.flexslider.js"></script>
    <script src="script/slider.js"></script>
</body>

</html>