<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TEST</title>
    <link rel="stylesheet" href="css/normalize.css" type="text/css">
    <link rel="stylesheet" href="css/flexslider.css" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Amaranth">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="css/style.css" type="text/css">

</head>

<body>
    <header class="header">
        <div class="header_ribbon"></div>
        <p class="header_p-promo">Livraison offerte à partir de 65 &euro;d'achat !</p>

        <div class="conteneur">
            <div class="header_div-init">
                <a href="home.php"> <img clas="header_logo" src="img/logo.png" alt="logo Cup og tea"></a>
                <div class="header_div-basket">
                    <a class="header_div-basket-name" href="">Mon panier</a>
                    <a href="" class="fas fa-shopping-cart header_div-basket-icon"></a>
                    <a class="header_div-basket-price" href="" id="headerTotalPrice">JS</a>
                </div>
            </div>
            <nav class="header_navbar">
                <a href="listing.php">Thés</a>
                <a href="listing.php">Grand crus</a>
                <a href="#">Accessoires</a>
                <a href="#">Epicerie</a>
                <a href="about.php">Notre histoire</a>
            </nav>
        </div>
    </header>