
    <main class="conteneur mainHome">
        <header class="mainHome-header">
            <h1>C'est noël, profitez-en !</h1>
            <img src="img/offre-noel.jpg" alt="Offre de noël" class="conteneur">
            <p class="mainHome_p-sub-text">Pour toute commande effetuée avant le 20 décembre</p>
        </header>
        <div class="flexslider">
            <ul class="slides">
                <li>
                    <img src="img/slider/1.jpg" />
                </li>
                <li>
                    <img src="img/slider/2.jpg" />
                </li>
            </ul>
        </div>
        <article class="mainHome_article-tea-chose">
            <h2 class="borderBar"><span>Choississez votre thé </span></h2>
            <div class="mainHome_div-tea-chose">
                <div>
                    <a href="listing.php#blacktea"><img src="img/tea/1.jpg" alt="thé noir">
                    <h3> Thé noir</h3></a>
                </div>
                <div>
                     <a href="listing.php#greentea"><img src="img/tea/2.jpg" alt="thé vert">
                    <h3>Thé vert</h3></a>
                </div>
                <div>
                     <a href="listing.php#oolong"><img src="img/tea/3.jpg" alt="oolong">
                    <h3>Oolong</h3></a>
                </div>
                <div>
                     <a href="listing#whitetea"><img src="img/tea/4.jpg" alt="thé blanc">
                    <h3>Thé blanc</h3></a>
                </div>
                <div>
                     <a href="listing#rooibos"><img src="img/tea/4.jpg" alt="rooibos">
                    <h3>Rooibos</h3></a>
                </div>
            </div>
        </article>
        <section class="mainHome_section-tea">
            <article class="mainHome_article-new-tea">
                <h2 class="borderBar"><span> Notre nouveauté</span></h2>
                <img src="img/product/product1.jpg" alt="">
                <h3>Thé au hammam</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam perferendis
                    nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                    tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                <div class="button-see-product">
                    <p>A partir de <br><span>8,50&euro;</span></p>
                    <a href="">Voir ce produit</a>
                </div>
            </article>
            <article class="mainHome_article-best-seller">
                <h2 class="borderBar"><span> Notre best-seller</span></h2>
                <img src="img/product/product2.jpg" alt="">
                <h3>Infusion Herboriste</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam perferendis
                    nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                    tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                <div class="button-see-product">
                    <p>A partir de <br><span>7,60&euro;</span></p>
                    <a href="">Voir ce produit</a>
                </div>
            </article>
            <article class="mainHome_article-loved-tea">
                <h2 class="borderBar"><span> Notre coup de coeur</span></h2>
                <img src="img/product/product3.jpg" alt="">
                <h3>Blue of London</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam perferendis
                    nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                    tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                <div class="button-see-product">
                    <p>A partir de <br><span>9,00&euro;</span></p>
                    <a href="">Voir ce produit</a>
                </div>
            </article>
        </section>
    </main>

