<main class="conteneur mainListing">
        <section class="mainListing_section-tea">
            <article class="mainListing_article-tea conteneur">
                <div class="clearfix">
                    <img src="img/tea/1.jpg" alt="">
                    <h2 class="borderBar" id="blacktea"><span>Thé noir </span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam
                        perferendis
                        nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                        tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                </div>
                <div class="mainListing_div-tea-chose">
                    <div>
                        <h3>Blue of London</h3>
                        <img src="img/product/product3_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>7,50&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Thé des lords</h3>
                        <img src="img/product/product6_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>8,20&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Thé des vahinés</h3>
                        <img src="img/product/product7_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>9,40&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                </div>
            </article>
            <article class="mainListing_article-tea">
                <div class="clearfix">
                    <img src="img/tea/2.jpg" alt="">
                    <h2 class="borderBar" id="greentea" ><span>Thé vert </span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam
                        perferendis
                        nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                        tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                </div>
                <div class="mainListing_div-tea-chose">
                    <div>
                        <h3>Thé du hammam </h3>
                        <img src="img/product/product1_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>8,40&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Vive le thé</h3>
                        <img src="img/product/product4_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>6,80&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Vive les alizés</h3>
                        <img src="img/product/product5_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>9,30&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                </div>
            </article>
            <article class="mainListing_article-tea">
                <div class="clearfix">
                    <img src="img/tea/3.jpg" alt="">
                    <h2 class="borderBar" id="oolong"><span>Oolong</span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam
                        perferendis
                        nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                        tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                </div>
                <div class="mainListing_div-tea-chose">
                    <div>
                        <h3>Vive les fêtes</h3>
                        <img src="img/product/product8_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>11,10&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Fleur d'oranger Oolong</h3>
                        <img src="img/product/product9_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>10,90&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Oolong 7 agrumes</h3>
                        <img src="img/product/product1_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>13,20&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                </div>
            </article>

            <article class="mainListing_article-tea">
                <div class="clearfix">
                    <img src="img/tea/4.jpg" alt="">
                    <h2 class="borderBar" id="whitetea"><span>Thé blanc </span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam
                        perferendis
                        nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                        tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                </div>
                <div class="mainListing_div-tea-chose">
                    <div>
                        <h3>Thé des songs blanc</h3>
                        <img src="img/product/product11_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>12,00&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Bai mu dan</h3>
                        <img src="img/product/product12_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>9,50&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Auguilles d'argent</h3>
                        <img src="img/product/product13_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>47,20&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                </div>
            </article>
            <article class="mainListing_article-tea">
                <div class="clearfix">
                    <img src="img/tea/5.jpg" alt="">
                    <h2 class="borderBar" id="rooibos"><span>Rooibos</span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, quo labore aperiam
                        perferendis
                        nesciunt, mollitia corporis quis quaerat dicta tempore officia placeat necessitatibus veritatis
                        tempora eveniet ipsam impedit perspiciatis praesentium.</p>
                </div>
                <div class="mainListing_div-tea-chose">
                    <div>
                        <img src="img/product/product14_big.jpg" alt="">
                        <h3>Roibos à la verveine</h3>
                        <div class="button-see-product">
                            <p>A partir de <br><span>7,00&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Spicy Passion</h3>
                        <img src="img/product/product15_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>9,00&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                    <div>
                        <h3>Rooibos des amants</h3>
                        <img src="img/product/product16_big.jpg" alt="">

                        <div class="button-see-product">
                            <p>A partir de <br><span>8,20&euro;</span></p>
                            <a href="">Voir ce produit</a>
                        </div>
                    </div>
                </div>
            </article>
        </section>
    </main>
